"""Fix execution snapshot comparison semantics."""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260930_0007"
down_revision: str | None = "20260928_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FIXED_FUNCTION = "CREATE OR REPLACE FUNCTION validate_execution_session_references()\nRETURNS trigger LANGUAGE plpgsql AS $$\nDECLARE\n  wi_owner uuid;\n  wi_kind text;\n  fp_owner uuid;\n  fp_work uuid;\n  fp_template boolean;\n  fp_deleted timestamptz;\n  rec_owner uuid;\n  rec_work uuid;\nBEGIN\n  IF TG_OP = 'UPDATE' THEN\n    IF (\n      NEW.owner_id <> OLD.owner_id OR\n      NEW.work_item_id <> OLD.work_item_id OR\n      NEW.focus_plan_id <> OLD.focus_plan_id OR\n      NEW.recommendation_id IS DISTINCT FROM OLD.recommendation_id OR\n      NEW.plan_snapshot_json::jsonb IS DISTINCT FROM OLD.plan_snapshot_json::jsonb OR\n      NEW.recommendation_snapshot_json::jsonb IS DISTINCT FROM OLD.recommendation_snapshot_json::jsonb OR\n      NEW.work_context_snapshot_json::jsonb IS DISTINCT FROM OLD.work_context_snapshot_json::jsonb OR\n      NEW.session_started_at <> OLD.session_started_at OR\n      NEW.created_at <> OLD.created_at\n    ) THEN\n      RAISE EXCEPTION 'execution session identity and snapshots are immutable';\n    END IF;\n    IF OLD.state IN ('completed', 'abandoned') AND NEW.state <> OLD.state THEN\n      RAISE EXCEPTION 'terminal execution session state is immutable';\n    END IF;\n    IF NEW.version <> OLD.version + 1 THEN\n      RAISE EXCEPTION 'execution session version must increment by one';\n    END IF;\n    RETURN NEW;\n  END IF;\n\n  SELECT owner_id, kind INTO wi_owner, wi_kind\n  FROM work_items\n  WHERE id = NEW.work_item_id AND deleted_at IS NULL;\n  IF NOT FOUND OR wi_owner <> NEW.owner_id OR wi_kind NOT IN ('chore', 'sprint') THEN\n    RAISE EXCEPTION 'invalid execution session work item reference';\n  END IF;\n\n  SELECT owner_id, work_item_id, is_template, deleted_at\n  INTO fp_owner, fp_work, fp_template, fp_deleted\n  FROM focus_plans\n  WHERE id = NEW.focus_plan_id;\n  IF NOT FOUND OR fp_owner <> NEW.owner_id OR fp_work <> NEW.work_item_id\n     OR fp_template OR fp_deleted IS NOT NULL THEN\n    RAISE EXCEPTION 'invalid execution session focus plan reference';\n  END IF;\n\n  IF NEW.recommendation_id IS NOT NULL THEN\n    SELECT owner_id, work_item_id INTO rec_owner, rec_work\n    FROM focus_plan_recommendations\n    WHERE id = NEW.recommendation_id;\n    IF NOT FOUND OR rec_owner <> NEW.owner_id OR rec_work <> NEW.work_item_id THEN\n      RAISE EXCEPTION 'invalid execution session recommendation reference';\n    END IF;\n  END IF;\n  RETURN NEW;\nEND;\n$$\n"
_OLD_FUNCTION = "CREATE OR REPLACE FUNCTION validate_execution_session_references()\nRETURNS trigger LANGUAGE plpgsql AS $$\nDECLARE\n  wi_owner uuid;\n  wi_kind text;\n  fp_owner uuid;\n  fp_work uuid;\n  fp_template boolean;\n  fp_deleted timestamptz;\n  rec_owner uuid;\n  rec_work uuid;\nBEGIN\n  IF TG_OP = 'UPDATE' THEN\n    IF (\n      NEW.owner_id <> OLD.owner_id OR\n      NEW.work_item_id <> OLD.work_item_id OR\n      NEW.focus_plan_id <> OLD.focus_plan_id OR\n      NEW.recommendation_id IS DISTINCT FROM OLD.recommendation_id OR\n      NEW.plan_snapshot_json IS DISTINCT FROM OLD.plan_snapshot_json OR\n      NEW.recommendation_snapshot_json IS DISTINCT FROM OLD.recommendation_snapshot_json OR\n      NEW.work_context_snapshot_json IS DISTINCT FROM OLD.work_context_snapshot_json OR\n      NEW.session_started_at <> OLD.session_started_at OR\n      NEW.created_at <> OLD.created_at\n    ) THEN\n      RAISE EXCEPTION 'execution session identity and snapshots are immutable';\n    END IF;\n    IF OLD.state IN ('completed', 'abandoned') AND NEW.state <> OLD.state THEN\n      RAISE EXCEPTION 'terminal execution session state is immutable';\n    END IF;\n    IF NEW.version <> OLD.version + 1 THEN\n      RAISE EXCEPTION 'execution session version must increment by one';\n    END IF;\n    RETURN NEW;\n  END IF;\n\n  SELECT owner_id, kind INTO wi_owner, wi_kind\n  FROM work_items\n  WHERE id = NEW.work_item_id AND deleted_at IS NULL;\n  IF NOT FOUND OR wi_owner <> NEW.owner_id OR wi_kind NOT IN ('chore', 'sprint') THEN\n    RAISE EXCEPTION 'invalid execution session work item reference';\n  END IF;\n\n  SELECT owner_id, work_item_id, is_template, deleted_at\n  INTO fp_owner, fp_work, fp_template, fp_deleted\n  FROM focus_plans\n  WHERE id = NEW.focus_plan_id;\n  IF NOT FOUND OR fp_owner <> NEW.owner_id OR fp_work <> NEW.work_item_id\n     OR fp_template OR fp_deleted IS NOT NULL THEN\n    RAISE EXCEPTION 'invalid execution session focus plan reference';\n  END IF;\n\n  IF NEW.recommendation_id IS NOT NULL THEN\n    SELECT owner_id, work_item_id INTO rec_owner, rec_work\n    FROM focus_plan_recommendations\n    WHERE id = NEW.recommendation_id;\n    IF NOT FOUND OR rec_owner <> NEW.owner_id OR rec_work <> NEW.work_item_id THEN\n      RAISE EXCEPTION 'invalid execution session recommendation reference';\n    END IF;\n  END IF;\n  RETURN NEW;\nEND;\n$$\n"


def upgrade() -> None:
    op.execute(sa.text(_FIXED_FUNCTION))


def downgrade() -> None:
    op.execute(sa.text(_OLD_FUNCTION))
